### ISSUE TITLE
Craft a new release

### ISSUE THREAD

**Issue by andygrunwald** [andygrunwald/go-gerrit#101]
Once we finished https://github.com/andygrunwald/go-gerrit/issues/100 we should release a new version.

See all the changes that happen since the last one: https://github.com/andygrunwald/go-gerrit/compare/0.5.2...master

**Comment by Jille** [comment]
SnoozeThis is pretty neat for this ;) (Especially with the [app](https://github.com/apps/snoozethis), because then it can take assigneeship).

(Wanna guess what I'm using your library for? ;))

@SnoozeThis #100

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/9b9pOIRYYFE) I will wait until https://github.com/andygrunwald/go-gerrit/issues/100 is closed and then add a comment.

**Comment by SnoozeThis** [comment]
Resolved.

**Comment by andygrunwald** [comment]
Solved via https://github.com/andygrunwald/go-gerrit/releases/tag/v1.0.0
