### ISSUE TITLE
Where to get the revisionID for the GetComment API ?

### ISSUE THREAD

**Issue by victory460** [andygrunwald/go-gerrit#102]
https://github.com/andygrunwald/go-gerrit/blob/ff14d0674afb9b172cf324af84466666c3ac55c9/changes_revision.go#L199

Where or how to get the `revisionID` for the GetComment API ?
Thanks a lot.

**Comment by dmitshur** [comment]
Take a look at the the linked Gerrit API documentation. If you want to find all comments on a given change, you might want to start with something like the [List Change Comments](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#list-change-comments) endpoint. From there, you’ll know the IDs of comments, and also the revision ID that each comment is associated with.

**Comment by victory460** [comment]
Thanks!
