### ISSUE TITLE
A few quirks with the API

### ISSUE THREAD

**Issue by perolausson** [andygrunwald/go-gerrit#16]
Now, this could be my own incompetency at doing golang, but there are a few things in the current API that I don't know how to handle best.

I'll take an example. If I query changes with LABELS/DETAILED-LABELS with the intent of checking if one or more changes have been **approved** then I was a bit stumped.

By approved I mean the final settings set on a change if a quality label is fully completed.

Here is what I had to do to check that:

```
func (c Change) Reviewed() bool {
	empty := gerrit.AccountInfo{}
	return empty != c.info.Labels.CodeReview.Approved   // info is a ChangeInfo
}
```

Now, this seems to be the case because that Approved thing is:
```

type AccountInfo struct {
	**AccountID int    `json:"_account_id"`**
	Name      string `json:"name,omitempty"`
	Email     string `json:"email,omitempty"`
	Username  string `json:"username,omitempty"`
}
```

If you can see AccountID will always be present, because it is never omitted.

Am I doing this totally wrong or is there a problem with the API? It seems very inelegant to me to compare with empty structs, especially since they aren't around when you need them.

**Comment by opalmer** [comment]
I have some code that does something similar to what you're trying to do that might help:

```go
package main

import (
	"github.com/andygrunwald/go-gerrit"
)

func main() {
	client, err := gerrit.NewClient("", nil)
	if err != nil {
		panic(err)
	}

	changes, _, err := client.Changes.QueryChanges(
		&gerrit.QueryChangeOptions{
			QueryOptions: gerrit.QueryOptions{
				Query: []string{"(is:open OR is:merged) AND after:2016-09-20"}},
			ChangeOptions: gerrit.ChangeOptions{
				AdditionalFields: []string{
					"DETAILED_LABELS",
					"DETAILED_ACCOUNTS"}}})
	if err != nil {
		panic(err)
	}

	for _, change := range *changes {
		for _, label := range change.Labels.CodeReview.All {
			...
		}
	}
}
```

I think all the info you're looking for is going to be somewhere under the `change.Labels.CodeReview` struct.  Generally speaking go-gerrit does not really modify the structures returned from Gerrit so if Gerrit's documentation references the info you're looking for then it's usually a matter of either tuning the query or fixing where you look for the data. Failing that I usually try using curl to figure out what I'm missing and to understand the general data structure better.

Let me know if you have more questions of if I've missed something.

**Comment by perolausson** [comment]
I think you are misunderstanding me. The issue is that the information sent back for a "Query Changes"  or "Get Change Detail" would normally not contain any information pertaining to approvals, if there are no approvals. In such cases the Json returned looks something like this:

  ....
          "url": "https://lh5.googleusercontent.com/-83BEYip0k-E/AAAAAAAAAAI/AAAAAAAAAAA/rybERPNrtdM/s100-p/photo.jpg",
        "height": 100
      }
    ]
  },
  "labels": {
    "Verified": {
      "values": {
        "-1": "Fails",
        " 0": "No score",
        "+1": "Verified"
      },
      "default_value": 0
    },
    "Code-Review": {
      "values": {
        "-2": "Do not submit",
        "-1": "I would prefer that you didn\u0027t submit this",
        " 0": "No score",
        "+1": "Looks good to me, but someone else must approve",
        "+2": "Looks good to me, approved"
      },
      "default_value": 0
    }
  },
  "permitted_labels": {
    "Code-Review": [
      "-1",
      " 0",
      "+1"
    ]
  },
  "removable_reviewers": [],
  "reviewers": {},
  "reviewer_updates": [],
  "messages": [
    {
      "id": "fc66fb4452cff31b138fbd67e3cef19953679a5b
  ....

I can see how you have through about this stuff. According to the documentation of the REST API a LabelInfo record should be returned and this would contain **optional** `AccountInfo `or `ApprovalInfo `records. But looking at `AccountInfo _account_id` is _not set as optional_, and therefore there will always be an `AccountInfo `returned by your API, even if there wasn't any returned by Gerrit.

So what I am saying is, I think you need to change the `_account_id `to be optional so that these fields will turn out to be nothing, if Gerrit didn't return anything. As it stands now, your API is basically saying that account_id 0 (admin?) has done some approvals when in fact they haven't.

**Comment by perolausson** [comment]
It's all ok from my point of view.
