### ISSUE TITLE
Move coverage to codecov.io?

### ISSUE THREAD

**Issue by opalmer** [andygrunwald/go-gerrit#24]
So on other projects I've moved from coveralls.io to codecov.io for a few reasons:

* The web interface for viewing coverage is more intuitive and generally provides more relevant information up front instead of having to dig deeper.
* Improved build reliability. I've seen several cases where backend issues with coveralls.io causes a build to fail (can't find repository, remote servers not responding, etc). Restarting a build attempt fixes the issue usually but it's still annoying especially for non-collaborators.
* coveralls.io comments in a PR don't provide a great deal of context especially at the diff level:
![screen shot 2016-10-16 at 10 24 22 am](https://cloud.githubusercontent.com/assets/255117/19418092/d8d33090-938a-11e6-8284-76a726487c4d.png)
compared to codecov.io:
![screen shot 2016-10-16 at 10 19 32 am](https://cloud.githubusercontent.com/assets/255117/19418096/eeb611fc-938a-11e6-9002-f71254d312e4.png)
* Coveralls adds a new comment for every commit, codecov makes one comment then edits it as you add more commits. This was configurable at one point for coveralls.io but it was buggy and didn't always work (comment not updated or a new comment was added anyway).
* In my experience codecov.io fixes bugs faster and has better overall support.

**Comment by andygrunwald** [comment]
This sounds good. I am open for a change.
Are you able to configure the repository to use codecov on your own? Or do you need support from me here?

**Comment by opalmer** [comment]
I probably can't modify the hooks without something equivalent to owner level access or something (based on my own experience with my own open source projects).  If you'd prefer not granting that, which I'd totally understand, I can fork the repo and get hooks working over there first then brink it back here for implementation.

**Comment by andygrunwald** [comment]
To be honest: I don`t even know how provide you more rights without transfering the repository to another user / organisation.
I can only add you as collaborator (as you are right now).

I just tried it (quick and dirty). See #25.
