### ISSUE TITLE
DiffContent.A/B/AB should be []string instead of string

### ISSUE THREAD

**Issue by egorse** [andygrunwald/go-gerrit#44]
As per https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#get-diff (and per run againts Gerrit 2.13.7) seems the DiffContent.A/B/AB should be []string.

The reason I don`t make the PR is - I am not sure was that always broken or its just changed in some newer Gerrit version

**Comment by shurcooL** [comment]
I believe so. I made some changes in my local copy to make things work (but haven’t had the chance to try to upstream my changes yet), and I have the following:

```Go
// DiffContent entity contains information about the content differences in a file.
type DiffContent struct {
	A      []string          `json:"a,omitempty"`
	B      []string          `json:"b,omitempty"`
	AB     []string          `json:"ab,omitempty"`
	EditA  DiffIntralineInfo `json:"edit_a,omitempty"`
	EditB  DiffIntralineInfo `json:"edit_b,omitempty"`
	Skip   int               `json:"skip,omitempty"`
	Common bool              `json:"common,omitempty"`
}
```

**Comment by egorse** [comment]
@shurcooL worth mentioning the DiffIntralineInfo should be [][2]int - but as well I am not sure that's is not Gerrit version dependand :roll_eyes:

**Comment by shurcooL** [comment]
I see. I haven't needed `EditA`/`EditB` fields yet, that's why I haven't touched them.

The README [specifies](https://github.com/andygrunwald/go-gerrit#what-about-the-version-compatibility-with-gerrit) which version of Gerrit API this library targets. It is 2.11.3-1230-gb8336f1 at this time. It should be possible to confirm whether that version also needs this change.

**Comment by egorse** [comment]
As per https://gerrit.googlesource.com/gerrit/+/v2.11/Documentation/rest-api-changes.txt#3068 seems its a bug - for A/B/AB and EditA/EditB
