### ISSUE TITLE
Proposal: Use Timestamp type for all time fields.

### ISSUE THREAD

**Issue by shurcooL** [andygrunwald/go-gerrit#55]
Right now, go-gerrit uses `string` type for all time fields. E.g.:

```Go
// ChangeInfo entity contains information about a change.
type ChangeInfo struct {
	...
	Created   string `json:"created"`
	Updated   string `json:"updated"`
	Submitted string `json:"submitted,omitempty"`
	...
}
```

Gerrit API documents time format at https://gerrit-review.googlesource.com/Documentation/rest-api.html#timestamp as:

> Timestamps are given in UTC and have the format "'yyyy-mm-dd hh:mm:ss.fffffffff'" where "'ffffffffff'" represents nanoseconds.

I propose we make a breaking API change and start using a `Timestamp` type for all time fields. E.g., something like this (details to be tweaked):

```Go
// ChangeInfo entity contains information about a change.
type ChangeInfo struct {
	...
	Created   Timestamp `json:"created"`
	Updated   Timestamp `json:"updated"`
	Submitted Timestamp `json:"submitted,omitempty"`
	...
}

// Timestamp represents an instant in time. It encodes to and from JSON as a Gerrit timestamp in UTC.
//
// Gerrit API docs: https://gerrit-review.googlesource.com/Documentation/rest-api.html#timestamp
type Timestamp struct {
	time.Time
}

func (t *Timestamp) UnmarshalJSON(b []byte) error {
	// Ignore null, like in the main JSON package.
	if string(b) == "null" {
		return nil
	}
	if len(b) < 2 || b[0] != '"' || b[len(b)-1] != '"' {
		return fmt.Errorf("failed to unmarshal non-string value %q as a Gerrit time", b)
	}
	tm, err := time.Parse(timeLayout, string(b[1:len(b)-1]))
	if err != nil {
		return err
	}
	t.Time = tm
	return nil
}

func (t Timestamp) MarshalJSON() ([]byte, error) { ... }

// Gerrit's timestamp layout is like time.RFC3339Nano, but with a space instead
// of the "T", and without a timezone (it's always in UTC).
// See https://gerrit-review.googlesource.com/Documentation/rest-api.html#timestamp.
const timeLayout = "2006-01-02 15:04:05.999999999"
```

I think making this change would significantly improve the usability of go-gerrit API.

It allows immediately using the `time.Time` methods on such fields, without having to parse each timestamp string and check for errors (something that should never happen, so factoring out the error checking into the go-gerrit library is very helpful at reducing boilerplate in user code).

go-github follows a similar pattern, it has a [`github.Timestamp`](https://godoc.org/github.com/google/go-github/github#Timestamp) type.

**Comment by andygrunwald** [comment]
Really good idea.
I like to work more with native go types than dealing with strings.
I guess, the reason why I am not implemented this is, that back in the days, when this lib was started, I just didn't know the `UnmarshalJSON ` functionality for own types.

I would be happy to accept a PR in this direction. And for such major improvements, I would consider a breaking change as ok.

**Comment by shurcooL** [comment]
Sounds good.

I've already implemented this locally (and been using it for some number of months), at least partially. I'm going to clean it up and send a PR.

**Comment by andygrunwald** [comment]
Sounds good. Thank you :)
