### ISSUE TITLE
All DELETE api calls returns error 400 (Bad request)

### ISSUE THREAD

**Issue by priteshpagar93** [andygrunwald/go-gerrit#76]
Functions ChangesService.DeleteTopic, ChangesService.DeleteDraftChange returns error '400 Bad Requests'.

RCA:
-----
In function NewRequest (inside gerrit.go), we set following headers:
Accept: application/json
Content-Type: application/json

This works for GET, POST api calls.
But as DELETE api calls does not need any content-type, they return 400.

**Comment by xobotyi** [comment]
Same stuff for `Changes.DeleteReviewer`

**Comment by andygrunwald** [comment]
Hey @priteshpagar93 and @xobotyi,

can you provide
- which Gerrit version?
- a piece of example code to reproduce the issue?

Thanks

**Comment by xobotyi** [comment]
@andygrunwald
- gerrit is 3.2.6
- example is pretty straightforward

```go
g, err := gerrit.NewClient(host, nil)
if err != nil {
	panic(err)
}

g.Authentication.SetBasicAuth(username, password)

// in case invalid credentials it will fail
_, _, err = g.Access.ListAccessRights(nil)
if err != nil {
	panic(err)
}

if _, err := g.Changes.DeleteReviewer("existing change id", "account id that set as reviewer"); err != nil {
	panic(err)
}
```

**Comment by xobotyi** [comment]
@andygrunwald made a PR fixing the issue

**Comment by andygrunwald** [comment]
Thanks both
