### ISSUE TITLE
Function DeleteDraftChange should be renamed as DeleteChange

### ISSUE THREAD

**Issue by priteshpagar93** [andygrunwald/go-gerrit#77]
Documentation about DeleteDraftChange() says that this function deletes a draft change.
But this function actually deletes a whole change.
(It implements API https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#delete-change)

Can we rename a function to avoid confusion.

**Comment by andygrunwald** [comment]
Thanks for raising the issue @priteshpagar93.
@wwade was that awesome to fix it in https://github.com/andygrunwald/go-gerrit/pull/95
