### ISSUE TITLE
SetReview support for --project option

### ISSUE THREAD

**Issue by sha4ever23** [andygrunwald/go-gerrit#79]
Hi,

I am looking for help with respect to finding equivalent of "--project" option of gerrit review command. 

Right now I don't find "project" setting available as part of "ReviewInput". 

gerrit review option --> 

////////////////////////////////////////////////////////////////////////////////////////////////
--project
-p
Name of the project the intended changes are contained within. This option must be supplied before the commit SHA-1 in order to take effect.
///////////////////////////////////////////// EOM//////////////////////////////////////////////

Could you please let me know how to do this?

regards
Shankar

**Comment by andygrunwald** [comment]
Hey @sha4ever23,

I assume you are talking about the API Endpoint [Set Review](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#set-review) and the struct [`ReviewInput`](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#review-input).

The endpoint URL is `/changes/{change-id}/revisions/{revision-id}/review'`.
In this case `{change-id}` contains already the project: [`"'<project>~<numericId>'"`](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#change-id).

Does this answer your question?

**Comment by andygrunwald** [comment]
Hey @sha4ever23,
I will close this ticket because I feel this question is answered.

if you think differently, let me know and I will reopen this ticket.
